using System.Text;
using System.Text.Json;
using iKeyd.Core.Chords;
using iKeyd.Core.Keymaps;

if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: iKeyd.ProfileCompiler <profile.json> <GeneratedProfile.g.cs>");
    return 2;
}

try
{
    var inputPath = Path.GetFullPath(args[0]);
    var outputPath = Path.GetFullPath(args[1]);
    if (!File.Exists(inputPath))
        throw new FileNotFoundException("Automation profile was not found.", inputPath);

    var generatedSource = ProfileCompiler.Compile(File.ReadAllText(inputPath));
    Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
    File.WriteAllText(outputPath, generatedSource, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    return 0;
}
catch (Exception exception)
{
    Console.Error.WriteLine($"iKeyd profile compilation failed: {exception.Message}");
    return 1;
}

internal static class ProfileCompiler
{
    private const int DefaultChordWindowMs = 40;
    private const int CompactKeyCount = Keymap<string>.CompactKeyCount;
    private const int MaxBehaviorStatementDepth = 32;

    public static string Compile(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
            throw new InvalidDataException("Profile JSON must not be empty.");

        using var document = JsonDocument.Parse(json);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("Profile root must be an object.");

        var chordWindowMs = DefaultChordWindowMs;
        if (root.TryGetProperty("source", out var source))
        {
            if (source.ValueKind != JsonValueKind.Object)
                throw new InvalidDataException("source must be an object.");
            if (source.TryGetProperty("chordWindowMs", out var chordWindow))
                chordWindowMs = chordWindow.GetInt32();
        }
        if (chordWindowMs < 0)
            throw new InvalidDataException("source.chordWindowMs must be non-negative.");

        var startupMode = root.TryGetProperty("startupMode", out var startupModeElement)
            ? startupModeElement.GetString() ?? throw new InvalidDataException("startupMode must be a string.")
            : "S";
        if (string.IsNullOrWhiteSpace(startupMode))
            throw new InvalidDataException("startupMode must not be empty.");
        var startupModeCode = startupMode.Trim().ToUpperInvariant();
        if (startupModeCode is not ("S" or "R" or "T" or "K"))
            throw new InvalidDataException($"Unsupported startupMode '{startupMode}' for the Windows app.");

        var clipboard = ParseClipboard(root);

        if (!root.TryGetProperty("singleStroke", out var singleRoot) || singleRoot.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("singleStroke must be an object.");
        if (!root.TryGetProperty("chords", out var chordRoot) || chordRoot.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("chords must be an object.");

        var hasBehaviors = root.TryGetProperty("behaviors", out var behaviorRoot);
        if (hasBehaviors && behaviorRoot.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("behaviors must be an object.");
        var hasUserBehaviors = root.TryGetProperty("behaviorDefinitions", out var userBehaviorRoot);
        if (hasUserBehaviors && userBehaviorRoot.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("behaviorDefinitions must be an object.");

        var modeNames = new List<string>();
        AddDistinctModeNames(modeNames, singleRoot);
        AddDistinctModeNames(modeNames, chordRoot);
        if (hasBehaviors)
            AddDistinctModeNames(modeNames, behaviorRoot);

        if (!modeNames.Any(name => string.Equals(name, "S", StringComparison.OrdinalIgnoreCase)) ||
            !modeNames.Any(name => string.Equals(name, "K", StringComparison.OrdinalIgnoreCase)))
        {
            throw new InvalidDataException("The Windows app requires both S and K keymaps.");
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using iKeyd.Core.Chords;");
        builder.AppendLine("using iKeyd.Core.Configuration;");
        builder.AppendLine("using iKeyd.Core.Keymaps;");
        builder.AppendLine("using iKeyd.Profiles.HotkeySkg.Modes;");
        builder.AppendLine();
        builder.AppendLine("namespace iKeyd.App;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedProfile");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly Keymap<string> SKeymap = CreateSKeymap();");
        builder.AppendLine("    private static readonly Keymap<string> KKeymap = CreateKKeymap();");
        builder.AppendLine();
        builder.AppendLine("    public static IKeydConfiguration Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        var profile = new AutomationProfile(");
        builder.AppendLine($"            chordWindowMs: {chordWindowMs},");
        builder.AppendLine("            keymaps: new AutomationKeymapProfile[]");
        builder.AppendLine("            {");

        foreach (var mode in modeNames)
        {
            var (singlesElement, chordsElement) = GetModeElements(singleRoot, chordRoot, mode);
            builder.AppendLine("                new AutomationKeymapProfile(");
            builder.AppendLine($"                    name: {Literal(mode)},");
            builder.AppendLine("                    singleMappings: new SingleMapping<string>[]");
            builder.AppendLine("                    {");
            foreach (var item in singlesElement.EnumerateObject())
            {
                var key = ParseKey(item.Name, $"singleStroke.{mode}");
                var output = item.Value.GetString() ?? string.Empty;
                builder.AppendLine($"                        new SingleMapping<string>({key.Expression}, {Literal(output)}),");
            }
            builder.AppendLine("                    },");
            builder.AppendLine("                    chordMappings: new ChordMapping<string>[]");
            builder.AppendLine("                    {");
            foreach (var item in chordsElement.EnumerateArray())
            {
                if (item.ValueKind != JsonValueKind.Array || item.GetArrayLength() != 3)
                    throw new InvalidDataException($"A chords.{mode} entry must contain [first, second, output].");
                var firstName = item[0].GetString() ?? throw new InvalidDataException("Chord first key is missing.");
                var secondName = item[1].GetString() ?? throw new InvalidDataException("Chord second key is missing.");
                var output = item[2].GetString() ?? string.Empty;
                var first = ParseKey(firstName, $"chords.{mode}");
                var second = ParseKey(secondName, $"chords.{mode}");
                builder.AppendLine($"                        new ChordMapping<string>({first.Expression}, {second.Expression}, {Literal(output)}),");
            }
            builder.AppendLine("                    },");
            builder.AppendLine("                    behaviorMappings: new BehaviorMappingProfile[]");
            builder.AppendLine("                    {");
            EmitBehaviorMappings(builder, mode, hasBehaviors, behaviorRoot);
            builder.AppendLine("                    }),");
        }

        builder.AppendLine("            },");
        builder.AppendLine($"            startupMode: {Literal(startupMode)},");
        builder.AppendLine("            hotkeys: new HotkeyBinding[]");
        builder.AppendLine("            {");
        if (root.TryGetProperty("hotkeys", out var hotkeysElement))
        {
            if (hotkeysElement.ValueKind != JsonValueKind.Array)
                throw new InvalidDataException("hotkeys must be an array.");
            foreach (var item in hotkeysElement.EnumerateArray())
            {
                if (item.ValueKind != JsonValueKind.Object)
                    throw new InvalidDataException("A hotkey entry must be an object.");
                var trigger = item.GetProperty("trigger").GetString()
                    ?? throw new InvalidDataException("A hotkey trigger must be a string.");
                var action = item.GetProperty("action").GetString()
                    ?? throw new InvalidDataException("A hotkey action must be a string.");
                builder.AppendLine($"                new HotkeyBinding({Literal(trigger)}, {Literal(action)}),");
            }
        }
        builder.AppendLine("            },");
        builder.AppendLine("            behaviorDefinitions: new UserBehaviorDefinitionProfile[]");
        builder.AppendLine("            {");
        if (hasUserBehaviors)
            EmitUserBehaviorDefinitions(builder, userBehaviorRoot, "                ");
        builder.AppendLine("            },");
        builder.AppendLine("            clipboard: new ClipboardHistoryProfile(");
        builder.AppendLine($"                history: {BoolLiteral(clipboard.History)},");
        builder.AppendLine($"                maxItems: {clipboard.MaxItems},");
        builder.AppendLine($"                persist: {BoolLiteral(clipboard.Persist)},");
        builder.AppendLine($"                images: {BoolLiteral(clipboard.Images)},");
        builder.AppendLine($"                encryption: {Literal(clipboard.Encryption)},");
        builder.AppendLine($"                cipher: {Literal(clipboard.Cipher)},");
        builder.AppendLine($"                directory: {(clipboard.Directory is null ? "null" : Literal(clipboard.Directory))}));");
        builder.AppendLine();
        builder.AppendLine($"        return new IKeydConfiguration(profile, InputMode.{startupModeCode}, SKeymap, KKeymap);");
        builder.AppendLine("    }");
        builder.AppendLine();

        EmitCompiledKeymapFactory(builder, "S", singleRoot, chordRoot);
        builder.AppendLine();
        EmitCompiledKeymapFactory(builder, "K", singleRoot, chordRoot);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitBehaviorMappings(
        StringBuilder builder,
        string mode,
        bool hasBehaviors,
        JsonElement behaviorRoot)
    {
        if (!hasBehaviors || !TryGetPropertyIgnoreCase(behaviorRoot, mode, out var behaviorsElement))
            return;
        if (behaviorsElement.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException($"behaviors.{mode} must be an object.");

        foreach (var item in behaviorsElement.EnumerateObject())
        {
            var key = ParseKey(item.Name, $"behaviors.{mode}");
            if (item.Value.ValueKind != JsonValueKind.Object)
                throw new InvalidDataException($"behaviors.{mode}.{item.Name} must be an object.");
            var behaviorName = item.Value.GetProperty("name").GetString()
                ?? throw new InvalidDataException($"behaviors.{mode}.{item.Name}.name must be a string.");
            if (!item.Value.TryGetProperty("arguments", out var argumentsElement) || argumentsElement.ValueKind != JsonValueKind.Array)
                throw new InvalidDataException($"behaviors.{mode}.{item.Name}.arguments must be an array.");

            var arguments = ReadStringArray(argumentsElement, $"behaviors.{mode}.{item.Name}.arguments");
            var options = new List<KeyValuePair<string, string>>();
            if (item.Value.TryGetProperty("options", out var optionsElement))
            {
                if (optionsElement.ValueKind != JsonValueKind.Object)
                    throw new InvalidDataException($"behaviors.{mode}.{item.Name}.options must be an object.");
                foreach (var option in optionsElement.EnumerateObject())
                    options.Add(new(option.Name, ReadBehaviorOptionValue(option.Value, $"behaviors.{mode}.{item.Name}.options.{option.Name}")));
            }

            builder.AppendLine($"                        new BehaviorMappingProfile({key.Expression}, new BehaviorInvocationProfile({Literal(behaviorName)}, new string[]");
            builder.AppendLine("                        {");
            foreach (var argument in arguments)
                builder.AppendLine($"                            {Literal(argument)},");
            builder.AppendLine("                        }, new KeyValuePair<string, string>[]");
            builder.AppendLine("                        {");
            foreach (var option in options)
                builder.AppendLine($"                            new KeyValuePair<string, string>({Literal(option.Key)}, {Literal(option.Value)}),");
            builder.AppendLine("                        })),");
        }
    }

    private static void EmitUserBehaviorDefinitions(StringBuilder builder, JsonElement root, string indent)
    {
        foreach (var item in root.EnumerateObject())
        {
            if (item.Value.ValueKind != JsonValueKind.Object)
                throw new InvalidDataException($"behaviorDefinitions.{item.Name} must be an object.");
            var definition = item.Value;
            if (!definition.TryGetProperty("parameters", out var parametersElement) || parametersElement.ValueKind != JsonValueKind.Array)
                throw new InvalidDataException($"behaviorDefinitions.{item.Name}.parameters must be an array.");
            var parameters = ReadStringArray(parametersElement, $"behaviorDefinitions.{item.Name}.parameters");

            builder.AppendLine($"{indent}new UserBehaviorDefinitionProfile(");
            builder.AppendLine($"{indent}    {Literal(item.Name)},");
            builder.AppendLine($"{indent}    new string[]");
            builder.AppendLine($"{indent}    {{");
            foreach (var parameter in parameters)
                builder.AppendLine($"{indent}        {Literal(parameter)},");
            builder.AppendLine($"{indent}    }},");
            builder.AppendLine($"{indent}    new UserBehaviorLocalProfile[]");
            builder.AppendLine($"{indent}    {{");
            if (definition.TryGetProperty("locals", out var localsElement))
            {
                if (localsElement.ValueKind != JsonValueKind.Object)
                    throw new InvalidDataException($"behaviorDefinitions.{item.Name}.locals must be an object.");
                foreach (var local in localsElement.EnumerateObject())
                {
                    if (local.Value.ValueKind is not (JsonValueKind.True or JsonValueKind.False))
                        throw new InvalidDataException($"behaviorDefinitions.{item.Name}.locals.{local.Name} must be boolean.");
                    builder.AppendLine($"{indent}        new UserBehaviorLocalProfile({Literal(local.Name)}, {(local.Value.GetBoolean() ? "true" : "false")}),");
                }
            }
            builder.AppendLine($"{indent}    }},");
            builder.AppendLine($"{indent}    new UserBehaviorHandlerProfile[]");
            builder.AppendLine($"{indent}    {{");
            if (definition.TryGetProperty("handlers", out var handlersElement))
            {
                if (handlersElement.ValueKind != JsonValueKind.Object)
                    throw new InvalidDataException($"behaviorDefinitions.{item.Name}.handlers must be an object.");
                foreach (var handler in handlersElement.EnumerateObject())
                {
                    if (handler.Value.ValueKind != JsonValueKind.Object)
                        throw new InvalidDataException($"behaviorDefinitions.{item.Name}.handlers.{handler.Name} must be an object.");
                    var handlerParameters = handler.Value.TryGetProperty("parameters", out var handlerParamsElement)
                        ? ReadStringArray(handlerParamsElement, $"behaviorDefinitions.{item.Name}.handlers.{handler.Name}.parameters")
                        : [];
                    if (!handler.Value.TryGetProperty("statements", out var statementsElement) || statementsElement.ValueKind != JsonValueKind.Array)
                        throw new InvalidDataException($"behaviorDefinitions.{item.Name}.handlers.{handler.Name}.statements must be an array.");

                    builder.AppendLine($"{indent}        new UserBehaviorHandlerProfile(");
                    builder.AppendLine($"{indent}            {Literal(handler.Name)},");
                    builder.AppendLine($"{indent}            new string[] {{ {string.Join(", ", handlerParameters.Select(Literal))} }},");
                    builder.AppendLine($"{indent}            new UserBehaviorStatementProfile[]");
                    builder.AppendLine($"{indent}            {{");
                    EmitStatements(builder, statementsElement, indent + "                ", 0);
                    builder.AppendLine($"{indent}            }}),");
                }
            }
            builder.AppendLine($"{indent}    }}),");
        }
    }

    private static void EmitStatements(StringBuilder builder, JsonElement statements, string indent, int depth)
    {
        if (depth > MaxBehaviorStatementDepth)
            throw new InvalidDataException("User behavior statement nesting exceeds the supported limit.");
        foreach (var statement in statements.EnumerateArray())
        {
            if (statement.ValueKind != JsonValueKind.Object)
                throw new InvalidDataException("A user behavior statement must be an object.");
            var op = statement.GetProperty("op").GetString()
                ?? throw new InvalidDataException("User behavior statement op must be a string.");
            var target = statement.TryGetProperty("target", out var targetElement) ? targetElement.GetString() : null;
            var value = statement.TryGetProperty("value", out var valueElement) ? valueElement.GetString() : null;
            var condition = statement.TryGetProperty("condition", out var conditionElement) ? conditionElement.GetString() : null;

            builder.AppendLine($"{indent}new UserBehaviorStatementProfile(");
            builder.AppendLine($"{indent}    op: {Literal(op)},");
            builder.AppendLine($"{indent}    target: {NullableLiteral(target)},");
            builder.AppendLine($"{indent}    value: {NullableLiteral(value)},");
            builder.AppendLine($"{indent}    condition: {NullableLiteral(condition)},");
            builder.AppendLine($"{indent}    thenStatements: new UserBehaviorStatementProfile[]");
            builder.AppendLine($"{indent}    {{");
            if (statement.TryGetProperty("then", out var thenElement))
            {
                if (thenElement.ValueKind != JsonValueKind.Array)
                    throw new InvalidDataException("User behavior statement then must be an array.");
                EmitStatements(builder, thenElement, indent + "        ", depth + 1);
            }
            builder.AppendLine($"{indent}    }},");
            builder.AppendLine($"{indent}    elseStatements: new UserBehaviorStatementProfile[]");
            builder.AppendLine($"{indent}    {{");
            if (statement.TryGetProperty("else", out var elseElement))
            {
                if (elseElement.ValueKind != JsonValueKind.Array)
                    throw new InvalidDataException("User behavior statement else must be an array.");
                EmitStatements(builder, elseElement, indent + "        ", depth + 1);
            }
            builder.AppendLine($"{indent}    }}),");
        }
    }

    private static void EmitCompiledKeymapFactory(StringBuilder builder, string mode, JsonElement singleRoot, JsonElement chordRoot)
    {
        var (singlesElement, chordsElement) = GetModeElements(singleRoot, chordRoot, mode);
        builder.AppendLine($"    private static Keymap<string> Create{mode}Keymap()");
        builder.AppendLine("    {");
        builder.AppendLine("        var single = new KeymapSlot<string>[Keymap<string>.CompactSingleSlotCount];");
        foreach (var item in singlesElement.EnumerateObject())
        {
            var key = ParseKey(item.Name, $"singleStroke.{mode}");
            var output = item.Value.GetString() ?? string.Empty;
            builder.AppendLine($"        single[{key.Code - 1}] = new KeymapSlot<string>({Literal(output)});");
        }
        builder.AppendLine("        var chords = new KeymapSlot<string>[Keymap<string>.CompactChordSlotCount];");
        var emittedChordIndices = new HashSet<int>();
        foreach (var item in chordsElement.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.Array || item.GetArrayLength() != 3)
                throw new InvalidDataException($"A chords.{mode} entry must contain [first, second, output].");
            var firstName = item[0].GetString() ?? throw new InvalidDataException("Chord first key is missing.");
            var secondName = item[1].GetString() ?? throw new InvalidDataException("Chord second key is missing.");
            var output = item[2].GetString() ?? string.Empty;
            var first = ParseKey(firstName, $"chords.{mode}");
            var second = ParseKey(secondName, $"chords.{mode}");
            var index = GetCompactChordIndex(first.Code, second.Code);
            if (emittedChordIndices.Add(index))
                builder.AppendLine($"        chords[{index}] = new KeymapSlot<string>({Literal(output)});");
        }
        builder.AppendLine("        return Keymap<string>.FromCompiledTables(single, chords);");
        builder.AppendLine("    }");
    }

    private static ClipboardSettings ParseClipboard(JsonElement root)
    {
        if (!root.TryGetProperty("clipboard", out var element))
            return ClipboardSettings.Default;
        if (element.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("clipboard must be an object.");

        var settings = ClipboardSettings.Default;
        var history = ReadOptionalBoolean(element, "history", settings.History);
        var maxItems = ReadOptionalInt32(element, "maxItems", settings.MaxItems);
        var persist = ReadOptionalBoolean(element, "persist", settings.Persist);
        var images = ReadOptionalBoolean(element, "images", settings.Images);
        var encryption = ReadOptionalString(element, "encryption", settings.Encryption).ToLowerInvariant();
        var cipher = ReadOptionalString(element, "cipher", settings.Cipher).ToLowerInvariant().Replace('_', '-');
        string? directory = null;
        if (element.TryGetProperty("directory", out var directoryElement))
        {
            if (directoryElement.ValueKind != JsonValueKind.String)
                throw new InvalidDataException("clipboard.directory must be a string.");
            directory = directoryElement.GetString();
            if (string.IsNullOrWhiteSpace(directory))
                throw new InvalidDataException("clipboard.directory must not be empty.");
        }

        if (maxItems <= 0)
            throw new InvalidDataException("clipboard.maxItems must be greater than zero.");
        if (encryption != "user")
            throw new InvalidDataException("clipboard.encryption currently supports only 'user'.");
        if (cipher is not ("auto" or "chacha20-poly1305"))
            throw new InvalidDataException("clipboard.cipher currently supports 'auto' or 'chacha20-poly1305'.");

        return new ClipboardSettings(history, maxItems, persist, images, encryption, cipher, directory);
    }

    private static bool ReadOptionalBoolean(JsonElement element, string name, bool fallback)
    {
        if (!element.TryGetProperty(name, out var value))
            return fallback;
        if (value.ValueKind is not (JsonValueKind.True or JsonValueKind.False))
            throw new InvalidDataException($"clipboard.{name} must be a boolean.");
        return value.GetBoolean();
    }

    private static int ReadOptionalInt32(JsonElement element, string name, int fallback)
    {
        if (!element.TryGetProperty(name, out var value))
            return fallback;
        if (value.ValueKind != JsonValueKind.Number || !value.TryGetInt32(out var result))
            throw new InvalidDataException($"clipboard.{name} must be an integer.");
        return result;
    }

    private static string ReadOptionalString(JsonElement element, string name, string fallback)
    {
        if (!element.TryGetProperty(name, out var value))
            return fallback;
        if (value.ValueKind != JsonValueKind.String)
            throw new InvalidDataException($"clipboard.{name} must be a string.");
        return value.GetString() ?? string.Empty;
    }

    private static (JsonElement Singles, JsonElement Chords) GetModeElements(JsonElement singleRoot, JsonElement chordRoot, string mode)
    {
        if (!TryGetPropertyIgnoreCase(singleRoot, mode, out var singlesElement))
            throw new InvalidDataException($"singleStroke.{mode} is missing from the profile.");
        if (!TryGetPropertyIgnoreCase(chordRoot, mode, out var chordsElement))
            throw new InvalidDataException($"chords.{mode} is missing from the profile.");
        if (singlesElement.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException($"singleStroke.{mode} must be an object.");
        if (chordsElement.ValueKind != JsonValueKind.Array)
            throw new InvalidDataException($"chords.{mode} must be an array.");
        return (singlesElement, chordsElement);
    }

    private static IReadOnlyList<string> ReadStringArray(JsonElement element, string location)
    {
        if (element.ValueKind != JsonValueKind.Array)
            throw new InvalidDataException($"{location} must be an array.");
        var result = new List<string>();
        foreach (var item in element.EnumerateArray())
        {
            if (item.ValueKind != JsonValueKind.String)
                throw new InvalidDataException($"{location} must contain strings.");
            result.Add(item.GetString()!);
        }
        return result;
    }

    private static void AddDistinctModeNames(List<string> names, JsonElement root)
    {
        foreach (var property in root.EnumerateObject())
        {
            if (!names.Any(name => string.Equals(name, property.Name, StringComparison.OrdinalIgnoreCase)))
                names.Add(property.Name);
        }
    }

    private static bool TryGetPropertyIgnoreCase(JsonElement element, string name, out JsonElement value)
    {
        foreach (var property in element.EnumerateObject())
        {
            if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                value = property.Value;
                return true;
            }
        }
        value = default;
        return false;
    }

    private static string ReadBehaviorOptionValue(JsonElement value, string location)
        => value.ValueKind switch
        {
            JsonValueKind.String => value.GetString() ?? string.Empty,
            JsonValueKind.Number => value.GetRawText(),
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            _ => throw new InvalidDataException($"{location} must be a string, number, or boolean.")
        };

    private static KeyInfo ParseKey(string key, string location)
    {
        if (string.IsNullOrWhiteSpace(key))
            throw new InvalidDataException($"{location} contains an empty key name.");

        if (!KeyId.TryParseCompact(key, out var code))
            throw new InvalidDataException($"{location} contains unsupported key '{key}' for the compiled Windows profile.");

        var numericCode = (int)code;
        if (numericCode is < 1 or > CompactKeyCount)
            throw new InvalidDataException($"{location} contains unsupported key '{key}' for the compiled Windows profile.");

        return new KeyInfo($"new KeyId(KeyCode.{code})", numericCode);
    }

    private static int GetCompactChordIndex(int firstCode, int secondCode)
    {
        var firstIndex = firstCode - 1;
        var secondIndex = secondCode - 1;
        if (firstIndex > secondIndex)
            (firstIndex, secondIndex) = (secondIndex, firstIndex);
        var rowOffset = firstIndex * CompactKeyCount - firstIndex * (firstIndex - 1) / 2;
        return rowOffset + secondIndex - firstIndex;
    }

    private static string NullableLiteral(string? value) => value is null ? "null" : Literal(value);
    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string Literal(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\': builder.Append("\\\\"); break;
                case '"': builder.Append("\\\""); break;
                case '\r': builder.Append("\\r"); break;
                case '\n': builder.Append("\\n"); break;
                case '\t': builder.Append("\\t"); break;
                case '\0': builder.Append("\\0"); break;
                default:
                    if (char.IsControl(character))
                        builder.Append("\\u").Append(((int)character).ToString("x4"));
                    else
                        builder.Append(character);
                    break;
            }
        }
        builder.Append('"');
        return builder.ToString();
    }

    private readonly record struct KeyInfo(string Expression, int Code);

    private readonly record struct ClipboardSettings(
        bool History,
        int MaxItems,
        bool Persist,
        bool Images,
        string Encryption,
        string Cipher,
        string? Directory)
    {
        public static ClipboardSettings Default { get; } = new(
            History: true,
            MaxItems: 20,
            Persist: true,
            Images: true,
            Encryption: "user",
            Cipher: "auto",
            Directory: null);
    }
}
