using System.Text;
using System.Text.Json;

if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: iKeyd.ProfileCompiler <profile.json> <GeneratedProfile.g.cs>");
    return 2;
}

try
{
    var inputPath = Path.GetFullPath(args[0]);
    var outputPath = Path.GetFullPath(args[1]);
    if (!File.Exists(inputPath))
        throw new FileNotFoundException("Automation profile was not found.", inputPath);

    var generatedSource = ProfileCompiler.Compile(File.ReadAllText(inputPath));
    Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
    File.WriteAllText(outputPath, generatedSource, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    return 0;
}
catch (Exception exception)
{
    Console.Error.WriteLine($"iKeyd profile compilation failed: {exception.Message}");
    return 1;
}

internal static class ProfileCompiler
{
    private const int DefaultChordWindowMs = 40;

    public static string Compile(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
            throw new InvalidDataException("Profile JSON must not be empty.");

        using var document = JsonDocument.Parse(json);
        var root = document.RootElement;
        if (root.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("Profile root must be an object.");

        var chordWindowMs = DefaultChordWindowMs;
        if (root.TryGetProperty("source", out var source))
        {
            if (source.ValueKind != JsonValueKind.Object)
                throw new InvalidDataException("source must be an object.");
            if (source.TryGetProperty("chordWindowMs", out var chordWindow))
                chordWindowMs = chordWindow.GetInt32();
        }
        if (chordWindowMs < 0)
            throw new InvalidDataException("source.chordWindowMs must be non-negative.");

        var startupMode = root.TryGetProperty("startupMode", out var startupModeElement)
            ? startupModeElement.GetString() ?? throw new InvalidDataException("startupMode must be a string.")
            : "S";
        if (string.IsNullOrWhiteSpace(startupMode))
            throw new InvalidDataException("startupMode must not be empty.");
        var startupModeCode = startupMode.Trim().ToUpperInvariant();
        if (startupModeCode is not ("S" or "R" or "T" or "K"))
            throw new InvalidDataException($"Unsupported startupMode '{startupMode}' for the Windows app.");

        if (!root.TryGetProperty("singleStroke", out var singleRoot) || singleRoot.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("singleStroke must be an object.");
        if (!root.TryGetProperty("chords", out var chordRoot) || chordRoot.ValueKind != JsonValueKind.Object)
            throw new InvalidDataException("chords must be an object.");

        var modeNames = new List<string>();
        AddDistinctModeNames(modeNames, singleRoot);
        AddDistinctModeNames(modeNames, chordRoot);

        if (!modeNames.Any(name => string.Equals(name, "S", StringComparison.OrdinalIgnoreCase)) ||
            !modeNames.Any(name => string.Equals(name, "K", StringComparison.OrdinalIgnoreCase)))
        {
            throw new InvalidDataException("The Windows app requires both S and K keymaps.");
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using iKeyd.Core.Chords;");
        builder.AppendLine("using iKeyd.Core.Configuration;");
        builder.AppendLine("using iKeyd.Profiles.HotkeySkg.Modes;");
        builder.AppendLine();
        builder.AppendLine("namespace iKeyd.App;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedProfile");
        builder.AppendLine("{");
        builder.AppendLine("    public static IKeydConfiguration Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        var profile = new AutomationProfile(");
        builder.AppendLine($"            chordWindowMs: {chordWindowMs},");
        builder.AppendLine("            keymaps: new AutomationKeymapProfile[]");
        builder.AppendLine("            {");

        foreach (var mode in modeNames)
        {
            if (!TryGetPropertyIgnoreCase(singleRoot, mode, out var singlesElement))
                throw new InvalidDataException($"singleStroke.{mode} is missing from the profile.");
            if (!TryGetPropertyIgnoreCase(chordRoot, mode, out var chordsElement))
                throw new InvalidDataException($"chords.{mode} is missing from the profile.");
            if (singlesElement.ValueKind != JsonValueKind.Object)
                throw new InvalidDataException($"singleStroke.{mode} must be an object.");
            if (chordsElement.ValueKind != JsonValueKind.Array)
                throw new InvalidDataException($"chords.{mode} must be an array.");

            builder.AppendLine("                new AutomationKeymapProfile(");
            builder.AppendLine($"                    name: {Literal(mode)},");
            builder.AppendLine("                    singleMappings: new SingleMapping<string>[]");
            builder.AppendLine("                    {");
            foreach (var item in singlesElement.EnumerateObject())
            {
                var key = KeyExpression(item.Name, $"singleStroke.{mode}");
                var output = item.Value.GetString() ?? string.Empty;
                builder.AppendLine($"                        new SingleMapping<string>({key}, {Literal(output)}),");
            }
            builder.AppendLine("                    },");
            builder.AppendLine("                    chordMappings: new ChordMapping<string>[]");
            builder.AppendLine("                    {");

            foreach (var item in chordsElement.EnumerateArray())
            {
                if (item.ValueKind != JsonValueKind.Array || item.GetArrayLength() != 3)
                    throw new InvalidDataException($"A chords.{mode} entry must contain [first, second, output].");

                var firstName = item[0].GetString() ?? throw new InvalidDataException("Chord first key is missing.");
                var secondName = item[1].GetString() ?? throw new InvalidDataException("Chord second key is missing.");
                var output = item[2].GetString() ?? string.Empty;
                var first = KeyExpression(firstName, $"chords.{mode}");
                var second = KeyExpression(secondName, $"chords.{mode}");
                builder.AppendLine($"                        new ChordMapping<string>({first}, {second}, {Literal(output)}),");
            }

            builder.AppendLine("                    }),");
        }

        builder.AppendLine("            },");
        builder.AppendLine($"            startupMode: {Literal(startupMode)},");
        builder.AppendLine("            hotkeys: new HotkeyBinding[]");
        builder.AppendLine("            {");

        if (root.TryGetProperty("hotkeys", out var hotkeysElement))
        {
            if (hotkeysElement.ValueKind != JsonValueKind.Array)
                throw new InvalidDataException("hotkeys must be an array.");

            foreach (var item in hotkeysElement.EnumerateArray())
            {
                if (item.ValueKind != JsonValueKind.Object)
                    throw new InvalidDataException("A hotkey entry must be an object.");
                var trigger = item.GetProperty("trigger").GetString()
                    ?? throw new InvalidDataException("A hotkey trigger must be a string.");
                var action = item.GetProperty("action").GetString()
                    ?? throw new InvalidDataException("A hotkey action must be a string.");
                builder.AppendLine($"                new HotkeyBinding({Literal(trigger)}, {Literal(action)}),");
            }
        }

        builder.AppendLine("            });");
        builder.AppendLine();
        builder.AppendLine($"        return new IKeydConfiguration(profile, InputMode.{startupModeCode});");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AddDistinctModeNames(List<string> names, JsonElement root)
    {
        foreach (var property in root.EnumerateObject())
        {
            if (!names.Any(name => string.Equals(name, property.Name, StringComparison.OrdinalIgnoreCase)))
                names.Add(property.Name);
        }
    }

    private static bool TryGetPropertyIgnoreCase(JsonElement element, string name, out JsonElement value)
    {
        foreach (var property in element.EnumerateObject())
        {
            if (string.Equals(property.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                value = property.Value;
                return true;
            }
        }

        value = default;
        return false;
    }

    private static string KeyExpression(string key, string location)
    {
        if (string.IsNullOrWhiteSpace(key))
            throw new InvalidDataException($"{location} contains an empty key name.");

        var normalized = key.Trim().ToUpperInvariant();
        string? token = null;
        if (normalized.Length == 1 && normalized[0] is >= 'A' and <= 'Z')
            token = normalized;
        else if (normalized.Length == 1 && normalized[0] is >= '0' and <= '9')
            token = $"Digit{normalized}";
        else if (normalized.Length is 2 or 3 && normalized[0] == 'F' &&
                 int.TryParse(normalized.AsSpan(1), out var functionNumber) &&
                 functionNumber is >= 1 and <= 12)
            token = normalized;
        else
            token = normalized switch
            {
                "SCOLON" => "SColon",
                "COLON" => "Colon",
                "COMMA" => "Comma",
                "DOT" => "Dot",
                "SLASH" => "Slash",
                "AT" => "At",
                _ => null
            };

        if (token is null)
            throw new InvalidDataException($"{location} contains unsupported key '{key}' for the compiled Windows profile.");

        return $"new KeyId(KeyCode.{token})";
    }

    private static string Literal(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\': builder.Append("\\\\"); break;
                case '"': builder.Append("\\\""); break;
                case '\r': builder.Append("\\r"); break;
                case '\n': builder.Append("\\n"); break;
                case '\t': builder.Append("\\t"); break;
                case '\0': builder.Append("\\0"); break;
                default:
                    if (char.IsControl(character))
                        builder.Append("\\u").Append(((int)character).ToString("x4"));
                    else
                        builder.Append(character);
                    break;
            }
        }
        builder.Append('"');
        return builder.ToString();
    }
}
