using System.Text;
using iKeyd.Core.Configuration;

internal static partial class ProfileCompiler
{
    public static string CompileFile(string inputPath)
    {
        if (string.IsNullOrWhiteSpace(inputPath))
            throw new ArgumentException("Profile input path must not be empty.", nameof(inputPath));

        var extension = Path.GetExtension(inputPath);
        var text = File.ReadAllText(inputPath);
        if (extension.Equals(".ikeyd", StringComparison.OrdinalIgnoreCase))
            return Compile(IKeydDslParser.Parse(text, inputPath));
        if (extension.Equals(".json", StringComparison.OrdinalIgnoreCase))
            return Compile(text);

        throw new InvalidDataException(
            $"Unsupported profile input '{inputPath}'. Expected a .ikeyd source file or legacy .json profile.");
    }

    public static string Compile(AutomationProfile profile)
    {
        ArgumentNullException.ThrowIfNull(profile);

        var startupMode = profile.StartupMode;
        var startupModeCode = startupMode.Trim().ToUpperInvariant();
        if (startupModeCode is not ("S" or "R" or "T" or "K"))
            throw new InvalidDataException($"Unsupported startupMode '{startupMode}' for the Windows app.");

        if (!profile.Keymaps.ContainsKey("S") || !profile.Keymaps.ContainsKey("K"))
            throw new InvalidDataException("The Windows app requires both S and K keymaps.");

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using iKeyd.Core.Chords;");
        builder.AppendLine("using iKeyd.Core.Configuration;");
        builder.AppendLine("using iKeyd.Core.Keymaps;");
        builder.AppendLine("using iKeyd.Profiles.HotkeySkg.Modes;");
        builder.AppendLine();
        builder.AppendLine("namespace iKeyd.App;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedProfile");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly Keymap<string> SKeymap = CreateSKeymap();");
        builder.AppendLine("    private static readonly Keymap<string> KKeymap = CreateKKeymap();");
        builder.AppendLine();
        builder.AppendLine("    public static IKeydConfiguration Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        var profile = new AutomationProfile(");
        builder.AppendLine($"            chordWindowMs: {profile.ChordWindowMs},");
        builder.AppendLine("            keymaps: new AutomationKeymapProfile[]");
        builder.AppendLine("            {");

        foreach (var keymap in profile.Keymaps.Values)
            EmitKeymap(builder, keymap);

        builder.AppendLine("            },");
        builder.AppendLine($"            startupMode: {Literal(startupMode)},");
        builder.AppendLine("            hotkeys: new HotkeyBinding[]");
        builder.AppendLine("            {");
        foreach (var hotkey in profile.Hotkeys)
            builder.AppendLine($"                new HotkeyBinding({Literal(hotkey.Trigger)}, {Literal(hotkey.Action)}),");
        builder.AppendLine("            },");
        builder.AppendLine("            behaviorDefinitions: new UserBehaviorDefinitionProfile[]");
        builder.AppendLine("            {");
        foreach (var definition in profile.BehaviorDefinitions.Values)
            EmitUserBehaviorDefinition(builder, definition, "                ");
        builder.AppendLine("            },");
        builder.AppendLine("            clipboard: new ClipboardHistoryProfile(");
        builder.AppendLine($"                history: {BoolLiteral(profile.Clipboard.History)},");
        builder.AppendLine($"                maxItems: {profile.Clipboard.MaxItems},");
        builder.AppendLine($"                persist: {BoolLiteral(profile.Clipboard.Persist)},");
        builder.AppendLine($"                images: {BoolLiteral(profile.Clipboard.Images)},");
        builder.AppendLine($"                encryption: {Literal(profile.Clipboard.Encryption)},");
        builder.AppendLine($"                cipher: {Literal(profile.Clipboard.Cipher)},");
        builder.AppendLine($"                directory: {(profile.Clipboard.Directory is null ? "null" : Literal(profile.Clipboard.Directory))}));");
        builder.AppendLine();
        builder.AppendLine($"        return new IKeydConfiguration(profile, InputMode.{startupModeCode}, SKeymap, KKeymap);");
        builder.AppendLine("    }");
        builder.AppendLine();

        EmitCompiledKeymapFactory(builder, profile.GetKeymap("S"));
        builder.AppendLine();
        EmitCompiledKeymapFactory(builder, profile.GetKeymap("K"));
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitKeymap(StringBuilder builder, AutomationKeymapProfile keymap)
    {
        builder.AppendLine("                new AutomationKeymapProfile(");
        builder.AppendLine($"                    name: {Literal(keymap.Name)},");
        builder.AppendLine("                    singleMappings: new SingleMapping<string>[]");
        builder.AppendLine("                    {");
        foreach (var mapping in keymap.SingleMappings)
        {
            var key = ParseKey(mapping.Key.Value, $"singleStroke.{keymap.Name}");
            builder.AppendLine($"                        new SingleMapping<string>({key.Expression}, {Literal(mapping.Output)}),");
        }
        builder.AppendLine("                    },");
        builder.AppendLine("                    chordMappings: new ChordMapping<string>[]");
        builder.AppendLine("                    {");
        foreach (var mapping in keymap.ChordMappings)
        {
            var first = ParseKey(mapping.First.Value, $"chords.{keymap.Name}");
            var second = ParseKey(mapping.Second.Value, $"chords.{keymap.Name}");
            builder.AppendLine($"                        new ChordMapping<string>({first.Expression}, {second.Expression}, {Literal(mapping.Output)}),");
        }
        builder.AppendLine("                    },");
        builder.AppendLine("                    behaviorMappings: new BehaviorMappingProfile[]");
        builder.AppendLine("                    {");
        foreach (var mapping in keymap.BehaviorMappings)
            EmitBehaviorMapping(builder, mapping);
        builder.AppendLine("                    }),");
    }

    private static void EmitBehaviorMapping(StringBuilder builder, BehaviorMappingProfile mapping)
    {
        var key = ParseKey(mapping.Key.Value, "behaviors");
        var invocation = mapping.Invocation;
        builder.AppendLine($"                        new BehaviorMappingProfile({key.Expression}, new BehaviorInvocationProfile({Literal(invocation.Name)}, new string[]");
        builder.AppendLine("                        {");
        foreach (var argument in invocation.Arguments)
            builder.AppendLine($"                            {Literal(argument)},");
        builder.AppendLine("                        }, new KeyValuePair<string, string>[]");
        builder.AppendLine("                        {");
        foreach (var option in invocation.Options)
            builder.AppendLine($"                            new KeyValuePair<string, string>({Literal(option.Key)}, {Literal(option.Value)}),");
        builder.AppendLine("                        })),");
    }

    private static void EmitUserBehaviorDefinition(
        StringBuilder builder,
        UserBehaviorDefinitionProfile definition,
        string indent)
    {
        builder.AppendLine($"{indent}new UserBehaviorDefinitionProfile(");
        builder.AppendLine($"{indent}    {Literal(definition.Name)},");
        builder.AppendLine($"{indent}    new string[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var parameter in definition.Parameters)
            builder.AppendLine($"{indent}        {Literal(parameter)},");
        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new UserBehaviorLocalProfile[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var local in definition.Locals)
        {
            builder.AppendLine(
                $"{indent}        new UserBehaviorLocalProfile({Literal(local.Name)}, {BoolLiteral(local.InitialValue)}),");
        }
        builder.AppendLine($"{indent}    }},");
        builder.AppendLine($"{indent}    new UserBehaviorHandlerProfile[]");
        builder.AppendLine($"{indent}    {{");
        foreach (var handler in definition.Handlers)
        {
            builder.AppendLine($"{indent}        new UserBehaviorHandlerProfile(");
            builder.AppendLine($"{indent}            {Literal(handler.Event)},");
            builder.AppendLine($"{indent}            new string[] {{ {string.Join(", ", handler.Parameters.Select(Literal))} }},");
            builder.AppendLine($"{indent}            new UserBehaviorStatementProfile[]");
            builder.AppendLine($"{indent}            {{");
            EmitStatements(builder, handler.Statements, indent + "                ", 0);
            builder.AppendLine($"{indent}            }}),");
        }
        builder.AppendLine($"{indent}    }}),");
    }

    private static void EmitStatements(
        StringBuilder builder,
        IReadOnlyList<UserBehaviorStatementProfile> statements,
        string indent,
        int depth)
    {
        if (depth > MaxBehaviorStatementDepth)
            throw new InvalidDataException("User behavior statement nesting exceeds the supported limit.");

        foreach (var statement in statements)
        {
            builder.AppendLine($"{indent}new UserBehaviorStatementProfile(");
            builder.AppendLine($"{indent}    op: {Literal(statement.Op)},");
            builder.AppendLine($"{indent}    target: {NullableLiteral(statement.Target)},");
            builder.AppendLine($"{indent}    value: {NullableLiteral(statement.Value)},");
            builder.AppendLine($"{indent}    condition: {NullableLiteral(statement.Condition)},");
            builder.AppendLine($"{indent}    thenStatements: new UserBehaviorStatementProfile[]");
            builder.AppendLine($"{indent}    {{");
            EmitStatements(builder, statement.Then, indent + "        ", depth + 1);
            builder.AppendLine($"{indent}    }},");
            builder.AppendLine($"{indent}    elseStatements: new UserBehaviorStatementProfile[]");
            builder.AppendLine($"{indent}    {{");
            EmitStatements(builder, statement.Else, indent + "        ", depth + 1);
            builder.AppendLine($"{indent}    }}),");
        }
    }

    private static void EmitCompiledKeymapFactory(StringBuilder builder, AutomationKeymapProfile keymap)
    {
        var mode = keymap.Name;
        builder.AppendLine($"    private static Keymap<string> Create{mode}Keymap()");
        builder.AppendLine("    {");
        builder.AppendLine("        var single = new KeymapSlot<string>[Keymap<string>.CompactSingleSlotCount];");
        foreach (var mapping in keymap.SingleMappings)
        {
            var key = ParseKey(mapping.Key.Value, $"singleStroke.{mode}");
            builder.AppendLine($"        single[{key.Code - 1}] = new KeymapSlot<string>({Literal(mapping.Output)});");
        }
        builder.AppendLine("        var chords = new KeymapSlot<string>[Keymap<string>.CompactChordSlotCount];");
        var emittedChordIndices = new HashSet<int>();
        foreach (var mapping in keymap.ChordMappings)
        {
            var first = ParseKey(mapping.First.Value, $"chords.{mode}");
            var second = ParseKey(mapping.Second.Value, $"chords.{mode}");
            var index = GetCompactChordIndex(first.Code, second.Code);
            if (emittedChordIndices.Add(index))
                builder.AppendLine($"        chords[{index}] = new KeymapSlot<string>({Literal(mapping.Output)});");
        }
        builder.AppendLine("        return Keymap<string>.FromCompiledTables(single, chords);");
        builder.AppendLine("    }");
    }
}