using System.Globalization;
using System.Text;
using System.Text.Json;
using iKeyd.Core.Configuration;

internal static class TypedMouseProfileCompiler
{
    public static string Compile(MouseMotionProfile profile)
    {
        ArgumentNullException.ThrowIfNull(profile);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using iKeyd.Core.Configuration;");
        builder.AppendLine();
        builder.AppendLine("namespace iKeyd.App;");
        builder.AppendLine();
        builder.AppendLine("internal static class GeneratedMouseProfile");
        builder.AppendLine("{");
        builder.AppendLine("    public static MouseMotionProfile Create() => new(");
        builder.AppendLine($"        {Literal(profile.Engine)},");
        builder.AppendLine($"        {profile.UpdateIntervalMs},");
        builder.AppendLine($"        {profile.PressMs},");
        builder.AppendLine($"        {profile.ReleaseMs},");
        builder.AppendLine($"        {Literal(profile.Curve)},");
        builder.AppendLine($"        {Number(profile.NormalSpeed)},");
        builder.AppendLine($"        {Number(profile.PrecisionSpeed)},");
        builder.AppendLine($"        {Number(profile.FineSpeed)},");
        builder.AppendLine($"        {Number(profile.FastSpeed)},");
        builder.AppendLine($"        {Literal(profile.Socd)},");
        builder.AppendLine($"        {profile.TapNudgePixels},");
        builder.AppendLine($"        {profile.MaxCatchupMs});");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Literal(string value) => JsonSerializer.Serialize(value);
    private static string Number(double value) => value.ToString("R", CultureInfo.InvariantCulture);
}
