using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using iKeyd.Compatibility.Tests;

namespace iKeyd.Windows.Tests;

/// <summary>
/// Runs hosted-safe layered Send scenarios against the real legacy process and
/// records injected key-down/key-up events. Scenario input uses a private marker,
/// so only output generated by the AHK runtime is observed.
/// </summary>
public sealed class LegacySendEventScenarioRunner : ICompatibilityScenarioRunner
{
    private const nuint ForeignMarker = (nuint)0x35792468U;
    private const byte VkNonConvert = 0x1D;
    private const byte NonConvertScanCode = 0x7B;
    private const byte VkConvert = 0x1C;
    private const byte ConvertScanCode = 0x79;
    private const byte VkSpace = 0x20;
    private const byte Vk3 = 0x33;
    private const uint KeyEventKeyUp = 0x0002;

    public string Name => "hotkeySKG.exe Send-events";

    public bool IsAvailable
    {
        get
        {
            if (!OperatingSystem.IsWindows())
                return false;
            var path = Environment.GetEnvironmentVariable(LegacyExecutableScenarioRunner.ExecutableEnvironmentVariable);
            return !string.IsNullOrWhiteSpace(path) && File.Exists(path);
        }
    }

    public async Task<ScenarioRunResult> RunAsync(
        CompatibilityScenario scenario,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(scenario);
        if (!OperatingSystem.IsWindows())
            throw new PlatformNotSupportedException("The legacy Send-event runner requires Windows.");
        if (!string.Equals(scenario.InitialState.Mode, "S", StringComparison.OrdinalIgnoreCase))
            throw new NotSupportedException("The first Send-event oracle runner uses the S keymap through hosted T mode.");
        if (scenario.InitialState.Modifiers.Count != 0)
            throw new NotSupportedException("Initial OS modifiers are not supported by the Send-event oracle runner.");
        if (scenario.InitialState.Layers.Any(layer => layer is not ("M" or "H" or "S")))
            throw new NotSupportedException("Hosted Send-event scenarios currently support only M/H/S initial layers.");

        var executable = ResolveExecutable();
        var sha256 = ComputeSha256(executable);
        VerifySha256(sha256);

        using var process = StartLegacyExecutable(executable);
        try
        {
            await Task.Delay(TimeSpan.FromMilliseconds(750), cancellationToken);
            if (process.HasExited)
                throw new InvalidOperationException($"Legacy executable exited during startup with code {process.ExitCode}.");

            // M+3 selects T mode while retaining the S keymap. Do this before
            // output capture so bootstrap control input cannot pollute the result.
            SendKey(VkNonConvert, NonConvertScanCode, keyUp: false);
            await Task.Delay(20, cancellationToken);
            SendKey(Vk3, 0, keyUp: false);
            SendKey(Vk3, 0, keyUp: true);
            await Task.Delay(20, cancellationToken);
            SendKey(VkNonConvert, NonConvertScanCode, keyUp: true);
            await Task.Delay(120, cancellationToken);

            using var capture = new InjectedKeyCapture(ForeignMarker);
            capture.Start();

            var heldLayers = ApplyInitialLayers(scenario.InitialState.Layers);
            try
            {
                await Task.Delay(30, cancellationToken);
                var stopwatch = Stopwatch.StartNew();
                foreach (var input in scenario.Input)
                {
                    await DelayUntilAsync(stopwatch, input.AtMs, cancellationToken);
                    SendScenarioInput(input);
                }

                if (!capture.WaitForCount(scenario.Expected.Events.Count, TimeSpan.FromSeconds(5)))
                {
                    throw new TimeoutException(
                        $"Legacy Send-event capture received {capture.Events.Count} of " +
                        $"{scenario.Expected.Events.Count} expected events.");
                }
            }
            finally
            {
                ReleaseLayers(heldLayers);
            }

            // A layer release must not emit an extra tap action after a consumed
            // function key. Keep capture alive briefly so such a mismatch is visible.
            await Task.Delay(100, cancellationToken);

            return new ScenarioRunResult
            {
                Runner = Name,
                ScenarioId = scenario.Id,
                Text = null,
                Events = capture.Events.ToList(),
                Actions = [],
                Metadata = new Dictionary<string, string>
                {
                    ["mode"] = "T",
                    ["legacyKeymap"] = "S",
                    ["layers"] = string.Join(string.Empty, scenario.InitialState.Layers),
                    ["scope"] = "legacy-process-injected-key-events",
                    ["sha256"] = sha256
                }
            };
        }
        finally
        {
            StopProcess(process);
        }
    }

    private static List<(byte VirtualKey, byte ScanCode)> ApplyInitialLayers(IReadOnlyList<string> layers)
    {
        var held = new List<(byte VirtualKey, byte ScanCode)>();
        foreach (var raw in layers)
        {
            var layer = raw.Trim().ToUpperInvariant();
            var key = layer switch
            {
                "M" => (VkNonConvert, NonConvertScanCode),
                "H" => (VkConvert, ConvertScanCode),
                "S" => (VkSpace, (byte)0),
                _ => throw new NotSupportedException($"Unsupported hosted layer '{raw}'.")
            };
            SendKey(key.Item1, key.Item2, keyUp: false);
            held.Add(key);
            Thread.Sleep(20);
        }
        return held;
    }

    private static void ReleaseLayers(IReadOnlyList<(byte VirtualKey, byte ScanCode)> layers)
    {
        for (var index = layers.Count - 1; index >= 0; index--)
        {
            var key = layers[index];
            SendKey(key.VirtualKey, key.ScanCode, keyUp: true);
            Thread.Sleep(20);
        }
    }

    private static void SendScenarioInput(ScenarioInputEvent input)
    {
        var virtualKey = ResolveVirtualKey(input.Key!);
        var scanCode = ResolveScanCode(input.Key!);
        SendKey(
            virtualKey,
            scanCode,
            string.Equals(input.Kind, "keyUp", StringComparison.OrdinalIgnoreCase));
    }

    private static byte ResolveVirtualKey(string key)
    {
        if (key.Length == 1)
        {
            var upper = char.ToUpperInvariant(key[0]);
            if (upper is >= 'A' and <= 'Z' or >= '0' and <= '9')
                return (byte)upper;
        }

        return key.Trim().ToUpperInvariant() switch
        {
            "KANA" => 0x15,
            "COMMA" => 0xBC,
            "SCOLON" => 0xBA,
            "DOT" => 0xBE,
            "SLASH" => 0xBF,
            _ => throw new NotSupportedException($"No virtual-key mapping for Send-event scenario key '{key}'.")
        };
    }

    private static byte ResolveScanCode(string key)
        => key.Trim().ToUpperInvariant() switch
        {
            "KANA" => 0x70,
            _ => 0
        };

    private static void SendKey(byte virtualKey, byte scanCode, bool keyUp)
        => NativeMethods.keybd_event(
            virtualKey,
            scanCode,
            keyUp ? KeyEventKeyUp : 0u,
            ForeignMarker);

    private static async Task DelayUntilAsync(Stopwatch stopwatch, long targetMs, CancellationToken cancellationToken)
    {
        var remaining = targetMs - stopwatch.ElapsedMilliseconds;
        if (remaining > 0)
            await Task.Delay(TimeSpan.FromMilliseconds(remaining), cancellationToken);
    }

    private static string ResolveExecutable()
    {
        var path = Environment.GetEnvironmentVariable(LegacyExecutableScenarioRunner.ExecutableEnvironmentVariable);
        if (string.IsNullOrWhiteSpace(path))
            throw new InvalidOperationException($"Set {LegacyExecutableScenarioRunner.ExecutableEnvironmentVariable} before running the Send-event oracle.");
        path = Path.GetFullPath(path);
        if (!File.Exists(path))
            throw new FileNotFoundException("Legacy executable was not found.", path);
        return path;
    }

    private static string ComputeSha256(string path)
    {
        using var stream = File.OpenRead(path);
        return Convert.ToHexString(SHA256.HashData(stream)).ToLowerInvariant();
    }

    private static void VerifySha256(string actual)
    {
        var expected = Environment.GetEnvironmentVariable(LegacyExecutableScenarioRunner.ExpectedSha256EnvironmentVariable);
        if (string.IsNullOrWhiteSpace(expected))
            expected = LegacyExecutableScenarioRunner.ReferenceSha256;
        if (!string.Equals(actual, expected.Trim(), StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException($"Legacy executable SHA-256 mismatch. Expected {expected}, actual {actual}.");
    }

    private static Process StartLegacyExecutable(string executable)
        => Process.Start(new ProcessStartInfo
        {
            FileName = executable,
            WorkingDirectory = Path.GetDirectoryName(executable) ?? Environment.CurrentDirectory,
            UseShellExecute = false
        }) ?? throw new InvalidOperationException("Could not start the legacy executable.");

    private static void StopProcess(Process process)
    {
        try
        {
            if (!process.HasExited)
            {
                process.Kill(entireProcessTree: true);
                process.WaitForExit(5000);
            }
        }
        catch
        {
            // Cleanup must not mask the compatibility result.
        }
    }

    private sealed class InjectedKeyCapture : IDisposable
    {
        private const int WhKeyboardLl = 13;
        private const uint WmQuit = 0x0012;
        private const uint WmKeyDown = 0x0100;
        private const uint WmKeyUp = 0x0101;
        private const uint WmSysKeyDown = 0x0104;
        private const uint WmSysKeyUp = 0x0105;
        private const uint PmNoRemove = 0;
        private const uint LlkhfInjected = 0x10;

        private readonly nuint _foreignMarker;
        private readonly object _gate = new();
        private readonly HookProc _hookProc;
        private readonly ManualResetEventSlim _started = new(false);
        private readonly List<ObservedKeyEvent> _events = [];
        private Thread? _thread;
        private uint _threadId;
        private nint _hook;
        private Exception? _startError;

        public InjectedKeyCapture(nuint foreignMarker)
        {
            _foreignMarker = foreignMarker;
            _hookProc = HookCallback;
        }

        public IReadOnlyList<ObservedKeyEvent> Events
        {
            get
            {
                lock (_gate)
                    return _events.ToArray();
            }
        }

        public void Start()
        {
            _thread = new Thread(ThreadMain) { IsBackground = true, Name = "iKeyd.LegacySendEventCapture" };
            _thread.Start();
            _started.Wait();
            if (_startError is not null)
                throw new InvalidOperationException("Could not start legacy Send-event capture.", _startError);
        }

        public bool WaitForCount(int count, TimeSpan timeout)
        {
            if (count == 0)
                return true;
            var stopwatch = Stopwatch.StartNew();
            while (stopwatch.Elapsed < timeout)
            {
                if (Events.Count >= count)
                    return true;
                Thread.Sleep(10);
            }
            return Events.Count >= count;
        }

        public void Dispose()
        {
            if (_thread is not null)
            {
                if (_threadId != 0)
                    NativeMethods.PostThreadMessageW(_threadId, WmQuit, 0, 0);
                if (!ReferenceEquals(Thread.CurrentThread, _thread))
                    _thread.Join(TimeSpan.FromSeconds(5));
            }
            _started.Dispose();
        }

        private void ThreadMain()
        {
            try
            {
                _threadId = NativeMethods.GetCurrentThreadId();
                NativeMethods.PeekMessageW(out _, 0, 0, 0, PmNoRemove);
                var module = NativeMethods.GetModuleHandleW(null);
                _hook = NativeMethods.SetWindowsHookExW(WhKeyboardLl, _hookProc, module, 0);
                if (_hook == 0)
                    throw new Win32Exception(Marshal.GetLastWin32Error(), "Could not install legacy Send-event hook.");
                _started.Set();

                while (true)
                {
                    var result = NativeMethods.GetMessageW(out var message, 0, 0, 0);
                    if (result == 0)
                        break;
                    if (result == -1)
                        throw new Win32Exception(Marshal.GetLastWin32Error(), "Legacy Send-event message loop failed.");
                    NativeMethods.TranslateMessage(ref message);
                    NativeMethods.DispatchMessageW(ref message);
                }
            }
            catch (Exception error)
            {
                _startError = error;
                _started.Set();
            }
            finally
            {
                if (_hook != 0)
                    NativeMethods.UnhookWindowsHookEx(_hook);
                _hook = 0;
                _threadId = 0;
            }
        }

        private nint HookCallback(int code, nuint wParam, nint lParam)
        {
            if (code >= 0 && (wParam is WmKeyDown or WmKeyUp or WmSysKeyDown or WmSysKeyUp))
            {
                var native = Marshal.PtrToStructure<KbdLlHookStruct>(lParam);
                if ((native.Flags & LlkhfInjected) != 0 && native.ExtraInfo != _foreignMarker)
                {
                    var kind = wParam is WmKeyUp or WmSysKeyUp ? "keyUp" : "keyDown";
                    lock (_gate)
                        _events.Add(new ObservedKeyEvent { Kind = kind, Key = KeyName(native.VirtualKey) });
                }
            }
            return NativeMethods.CallNextHookEx(_hook, code, wParam, lParam);
        }

        private static string KeyName(uint virtualKey)
        {
            if (virtualKey is >= 0x41 and <= 0x5A)
                return ((char)virtualKey).ToString();
            if (virtualKey is >= 0x70 and <= 0x7B)
                return $"F{virtualKey - 0x70 + 1}";

            return virtualKey switch
            {
                0x08 => "Backspace",
                0x09 => "Tab",
                0x0D => "Enter",
                0x10 => "Shift",
                0x11 => "Control",
                0x12 => "Alt",
                0x1B => "Escape",
                0x20 => "Space",
                0x21 => "PageUp",
                0x22 => "PageDown",
                0x23 => "End",
                0x24 => "Home",
                0x25 => "Left",
                0x26 => "Up",
                0x27 => "Right",
                0x28 => "Down",
                0x2D => "Insert",
                0x2E => "Delete",
                0x5B => "LWin",
                0x5D => "AppsKey",
                _ => $"VK_{virtualKey:X2}"
            };
        }
    }

    private delegate nint HookProc(int code, nuint wParam, nint lParam);

    [StructLayout(LayoutKind.Sequential)]
    private struct KbdLlHookStruct
    {
        public uint VirtualKey;
        public uint ScanCode;
        public uint Flags;
        public uint Time;
        public nuint ExtraInfo;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct NativePoint { public int X; public int Y; }

    [StructLayout(LayoutKind.Sequential)]
    private struct NativeMessage
    {
        public nint Window;
        public uint Message;
        public nuint WParam;
        public nint LParam;
        public uint Time;
        public NativePoint Point;
        public uint Private;
    }

    private static class NativeMethods
    {
        [DllImport("user32.dll")]
        public static extern void keybd_event(byte virtualKey, byte scanCode, uint flags, nuint extraInfo);

        [DllImport("kernel32.dll")]
        public static extern uint GetCurrentThreadId();

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
        public static extern nint GetModuleHandleW(string? moduleName);

        [DllImport("user32.dll", SetLastError = true)]
        public static extern nint SetWindowsHookExW(int hookId, HookProc hookProc, nint module, uint threadId);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool UnhookWindowsHookEx(nint hook);

        [DllImport("user32.dll")]
        public static extern nint CallNextHookEx(nint hook, int code, nuint wParam, nint lParam);

        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool PostThreadMessageW(uint threadId, uint message, nuint wParam, nint lParam);

        [DllImport("user32.dll", SetLastError = true)]
        public static extern int GetMessageW(out NativeMessage message, nint window, uint min, uint max);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool TranslateMessage(ref NativeMessage message);

        [DllImport("user32.dll")]
        public static extern nint DispatchMessageW(ref NativeMessage message);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool PeekMessageW(out NativeMessage message, nint window, uint min, uint max, uint removeMessage);
    }
}
