using System.Globalization;
using System.Text;
using System.Text.Json;
using iKeyd.Core.Configuration;

if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: iKeyd.MouseProfileCompiler <profile.json> <GeneratedMouseProfile.g.cs>");
    return 2;
}

try
{
    var inputPath = Path.GetFullPath(args[0]);
    var outputPath = Path.GetFullPath(args[1]);
    if (!File.Exists(inputPath))
        throw new FileNotFoundException("Automation profile was not found.", inputPath);

    using var document = JsonDocument.Parse(File.ReadAllText(inputPath));
    var profile = MouseMotionProfileJson.Parse(document.RootElement);
    var source = Generate(profile);

    Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
    File.WriteAllText(outputPath, source, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    return 0;
}
catch (Exception exception)
{
    Console.Error.WriteLine($"iKeyd mouse profile compilation failed: {exception.Message}");
    return 1;
}

static string Generate(MouseMotionProfile profile)
{
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine("using iKeyd.Core.Configuration;");
    builder.AppendLine();
    builder.AppendLine("namespace iKeyd.App;");
    builder.AppendLine();
    builder.AppendLine("internal static class GeneratedMouseProfile");
    builder.AppendLine("{");
    builder.AppendLine("    public static MouseMotionProfile Create() => new(");
    builder.AppendLine($"        {Literal(profile.Engine)},");
    builder.AppendLine($"        {profile.UpdateIntervalMs},");
    builder.AppendLine($"        {profile.PressMs},");
    builder.AppendLine($"        {profile.ReleaseMs},");
    builder.AppendLine($"        {Literal(profile.Curve)},");
    builder.AppendLine($"        {Number(profile.NormalSpeed)},");
    builder.AppendLine($"        {Number(profile.PrecisionSpeed)},");
    builder.AppendLine($"        {Number(profile.FineSpeed)},");
    builder.AppendLine($"        {Number(profile.FastSpeed)},");
    builder.AppendLine($"        {Literal(profile.Socd)},");
    builder.AppendLine($"        {profile.TapNudgePixels},");
    builder.AppendLine($"        {profile.MaxCatchupMs});");
    builder.AppendLine("}");
    return builder.ToString();
}

static string Literal(string value) => JsonSerializer.Serialize(value);
static string Number(double value) => value.ToString("R", CultureInfo.InvariantCulture);
